# Generated by Django 4.1.5 on 2023-07-18 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('code', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name="code de l'offre")),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('pays', models.CharField(default='Guinée', max_length=15)),
                ('doc1', models.FileField(upload_to='documents/')),
                ('doc2', models.FileField(upload_to='documents/')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entrep', models.CharField(max_length=115, verbose_name="Nom de l'entreprise")),
                ('adresse_entrep', models.CharField(max_length=200)),
                ('email_entrep', models.EmailField(max_length=254, verbose_name="email de l'entreprise")),
                ('telephone', models.CharField(max_length=10)),
                ('activite', models.CharField(max_length=115, verbose_name="domaine d'activité")),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.FileField(upload_to='documents/')),
                ('retenu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.entreprise')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.offre')),
            ],
        ),
    ]
