# Generated by Django 4.2.3 on 2023-08-07 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='proposition',
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidature',
            name='proposition1',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='proposition2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='proposition3',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='proposition4',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='proposition5',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='refuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offre',
            name='doc3',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AddField(
            model_name='offre',
            name='doc4',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AddField(
            model_name='offre',
            name='doc5',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse_entrep',
            field=models.CharField(max_length=200, verbose_name="adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='offre',
            name='doc1',
            field=models.FileField(upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='doc2',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
