# Generated by Django 4.2.3 on 2023-08-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_remove_candidature_proposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='doc1',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
