# Generated by Django 4.2.3 on 2023-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_remove_candidature_date_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_limite',
            field=models.DateTimeField(),
        ),
    ]
