# Generated by Django 4.2.3 on 2023-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_alter_offre_date_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='heure_limite',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
