# Generated by Django 4.2.3 on 2023-08-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_offre_heure_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
