# Generated by Django 4.2.3 on 2023-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_entreprise_immatriculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='idtel',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
