# Generated by Django 4.2.3 on 2023-10-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0009_entreprise_idtel"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="secteur",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="domaine d'activité"
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="activite",
            field=models.CharField(
                blank=True, max_length=115, verbose_name="domaine d'activité"
            ),
        ),
    ]
