# Generated by Django 4.2.3 on 2024-05-17 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0010_entreprise_secteur_alter_entreprise_activite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offre',
            new_name='Marche_public',
        ),
    ]
