# Generated by Django 4.2.3 on 2024-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0012_alter_marche_public_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche_public',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name="code de l'offre"),
        ),
    ]
