# Generated by Django 4.2.3 on 2024-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0013_alter_marche_public_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="marche_public",
            name="ouvert",
            field=models.BooleanField(default=False),
        ),
    ]
