# Generated by Django 4.2.3 on 2023-07-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeur',
            old_name='utilsateur',
            new_name='utilisateur',
        ),
    ]
