# Generated by Django 4.2.3 on 2023-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
