# Generated by Django 4.2.3 on 2023-08-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employeur',
        ),
    ]
