# Generated by Django 4.2.3 on 2023-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeur', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='code1',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='employeur',
            name='code2',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
