# Generated by Django 4.2.3 on 2023-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeur', '0004_employeur_code1_employeur_code2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeur',
            old_name='fonction',
            new_name='fonction1',
        ),
        migrations.AddField(
            model_name='employeur',
            name='fonction2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
