# Generated by Django 4.2.3 on 2024-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeur', '0005_rename_fonction_employeur_fonction1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='email1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeur',
            name='email2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
