# Generated by Django 4.2.3 on 2024-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeur', '0006_employeur_email1_employeur_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='activer',
            field=models.BooleanField(default=False),
        ),
    ]
