# Generated by Django 4.2.3 on 2024-06-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeur', '0007_employeur_activer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeur',
            old_name='activer',
            new_name='active_offres',
        ),
    ]
