# Generated by Django 4.2.3 on 2024-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employeur', '0008_rename_activer_employeur_active_offres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeur',
            name='active_offres',
        ),
        migrations.AddField(
            model_name='employeur',
            name='active_offre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
